#!/bin/sh

### BEGIN INIT INFO
# Provides:          python3-http-server
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start python3-http-server at boot time
# Description:       Enable service provided by python3-http-server.
### END INIT INFO

NAME=python3-http-server
DAEMON=/usr/bin/python3
DAEMON_ARGS="-m http.server 8081"
WORKING_DIR=/tmp
PIDFILE=/var/run/$NAME.pid
USER=www-data

. /lib/lsb/init-functions

do_start()
{
  log_daemon_msg "Starting $NAME daemon"
  start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --chuid $USER --chdir $WORKING_DIR --exec $DAEMON $DAEMON_ARGS
  log_end_msg $?
}

do_stop()
{
  log_daemon_msg "Stopping $NAME daemon"
  start-stop-daemon --stop --pidfile $PIDFILE
  log_end_msg $?
}

case "$1" in
  start|stop)
    do_${1}
    ;;
  restart|reload|force-reload)
    do_stop
    do_start
    ;;
  status)
    status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|reload|force-reload|status}"
    exit 1
    ;;
esac

exit 0
